// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(OnlineMovieDBContext))]
    partial class OnlineMovieDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Country", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Україна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "США"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Китай"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Індія"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Бразилія"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Німеччина"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Японія"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Франція"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Канада"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Італія"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Австралія"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Іспанія"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Мексика"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Південна Корея"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Індонезія"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Нідерланди"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Польща"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Швеція"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Швейцарія"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Британія"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Шотландія"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Англія"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ірландія"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback", t =>
                        {
                            t.HasCheckConstraint("Text_check", "[Text] <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Rating = 4.0,
                            Text = "Чудовий фільм",
                            UserId = "d1901b2435594da2a255db13fc57509b"
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            Rating = 4.0,
                            Text = "Фільм дуже сподобався",
                            UserId = "c86dc56aedf549f6afe5ceb4d414ebf1"
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 2,
                            Rating = 4.0,
                            Text = "Один з найкащих фільмів",
                            UserId = "028582c83a914a45b330b5234f4131fb"
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 2,
                            Rating = 5.0,
                            Text = "Фільм дуже сподобався",
                            UserId = "eb05f9548a2c4cf8adcc2be7305fc732"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Genre", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Екшн"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Пригоди"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Комедія"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Жахи"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Фентезі"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Романтика"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Трилер"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Кримінал"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Вестерн"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Воєнний"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Документальний"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Містика"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Мюзикл"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Аніме"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Спорт"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Історичний"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Біографія"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Детектив"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Хоррор"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Мелодрама"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("Name");

                    b.ToTable("Image", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check2");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Name = "78f6bd3dff214a149d2b819d2bb2f596.jpg"
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            Name = "e8709c9c252c4d0680054104be5d200a.jpg"
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            Name = "9d02da5822204216838b18237d0752bc.jpg"
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            Name = "cadc26fad170460196200194d40a718a.jpg"
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 1,
                            Name = "9a43056743774ef592a36559134f5be2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 1,
                            Name = "d14d399aa31d45678ad8cb2b317d6d5b.jpg"
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 1,
                            Name = "342c6b26fb544d43914ad1060677b2b8.jpg"
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 2,
                            Name = "2d0627d1199a466c8486c07dc446e1b1.jpg"
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 2,
                            Name = "fc404272f1b34d2e9f887073b58831b9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 2,
                            Name = "3ad737531a5c4b35b0bf99250208badd.jpg"
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 2,
                            Name = "c0299b7d354d4aa79f21d7e7b49519a5.jpg"
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 2,
                            Name = "978e2ab0753c4161bbd7f3af865df208.jpg"
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 2,
                            Name = "80c0e4e646d8435e9d7a4e9211a3be96.jpg"
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 2,
                            Name = "3484dbfface144648621281a62b40d81.jpg"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Poster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("noposter.jpeg");

                    b.Property<int>("PremiumId")
                        .HasColumnType("int");

                    b.Property<int>("QualityId")
                        .HasColumnType("int");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("PremiumId");

                    b.HasIndex("QualityId");

                    b.ToTable("Movie", t =>
                        {
                            t.HasCheckConstraint("MovieUrl_check", "[MovieUrl] <> ''");

                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check3");

                            t.HasCheckConstraint("OriginalName_check", "[OriginalName] <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 2,
                            Date = new DateTime(1995, 4, 25, 2, 57, 0, 0, DateTimeKind.Unspecified),
                            Description = "Фільм, що розповідає про боротьбу Шотландського королівства за незалежність проти англійського панування. Головний герой фільму — Вільям Воллес, ватажок шотландців, у виконанні Мела Гібсона.одії фільму починаються 1280 року. Це історія легендарного національного шотландського героя Вільяма Воллеса, який присвятив себе боротьбі з англійцями за часів короля Едуарда Довгоногого. Вільям рано втратив батька, що загинув від рук англійців, але його дядько зумів дати хлопцеві навчання в Європі. На батьківщину Вільям повертається вже дорослим чоловіком, що мріє завести родину і жити мирним життям. Та доля вирішила інакше. Його наречену вбили англійці, і він почав свій «хрестовий похід» за свободу.",
                            MovieUrl = "https://pixel.stream.voidboost.cc/52806ed4b4d47c4a8297f9e4983a9659:2024022221:4c97894d-562e-4330-9154-0facb485bda1/7/8/1/6/3/byf31.mp4",
                            Name = "Хоробре серце",
                            OriginalName = "Braveheart",
                            Poster = "82ff372d46f44895af282106fe13a201.jpg",
                            PremiumId = 1,
                            QualityId = 3,
                            TrailerUrl = "https://www.youtube.com/watch?v=277chVHPQSA&t=39s"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Date = new DateTime(2010, 7, 22, 2, 28, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ми звикли, що в нашому розумінні злодій - це людина здатна вкрасти якісь цінності або гроші. Сюжет фантастичного бойовика «Початок» розповідає про злодіїв здатних вкрасти ідею прямо у людини з підсвідомості. Одним з таких є головний герой фільму Домінік Кобб. Після того як його дружина померла, він змушений ховатися, і не може навіть повернутися в країну, щоб побачити дітей. Якось раз Кобб отримує дуже неординарне замовлення: йому потрібно не вкрасти, а навпаки впровадити нову ідею в підсвідомість людини. Домініку не надто хотітися братися за цю справу, але замовник в обмін пропонує можливість повернутися додому. Заручившись підтримкою професіоналів цієї справи, Кобб починає розробляти план як все провернути. Все потрібно дуже добре продумати, адже злодіям доведеться відтворити багатошарову реальність в підсвідомості об'єкта, в результаті чого межі можуть почати стиратися.",
                            MovieUrl = "https://aura.stream.voidboost.cc/e86eaadc35a0ecfb807054393e269605:2024022217:a95fa9f9-d7d0-4039-ad6f-4e785486da15/5/9/1/7/7/to9f8.mp4",
                            Name = "Початок",
                            OriginalName = "Inception",
                            Poster = "7d4159900afd4481881c42483b369f3e.jpg",
                            PremiumId = 2,
                            QualityId = 2,
                            TrailerUrl = "https://www.youtube.com/watch?v=85Zz1CCXyDI"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.MovieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 18,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 4,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 2,
                            MovieId = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Premium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Premium", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check4");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Free",
                            Rate = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Light",
                            Rate = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Midle",
                            Rate = 40
                        },
                        new
                        {
                            Id = 5,
                            Name = "Full",
                            Rate = 60
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Quality", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web-DL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "1080p"
                        },
                        new
                        {
                            Id = 3,
                            Name = "720p"
                        },
                        new
                        {
                            Id = 5,
                            Name = "480p"
                        },
                        new
                        {
                            Id = 6,
                            Name = "2K"
                        },
                        new
                        {
                            Id = 7,
                            Name = "4K"
                        },
                        new
                        {
                            Id = 8,
                            Name = "8K"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Staf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("nophoto.jpeg");

                    b.Property<bool>("IsOscar")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Staf", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check6");

                            t.HasCheckConstraint("Surname_check", "[Surname] <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1956, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 2,
                            Description = "Народився 3 січня 1956 року.\r\n\r\nСин ірландців-католиків Гаттона Гібсона та Ен Райлі Гібсон, яка народилася в парафії Колм-Кіллє графства Лонгфорд, Ірландія. Його бабця по батькові Ева Майлот була австралійською оперною співачкою. Мел народився у місті Пікскілл (округ Вестчестер, штат Нью-Йорк) і був шостим з одинадцяти дітей. Один із молодших братів Мела, Донал, також актор.",
                            ImageName = "d5d49574945f45c8be24f00cc02923af.webp",
                            IsOscar = true,
                            Name = "Мел",
                            Surname = "Гибсон"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1963, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 21,
                            Description = "Народився у сім'ї лікаря. У дитинстві подорожував між трьома країнами — Філіппінами, Сингапуром і Францією. Вищу освіту Енгус отримав у стінах Університету Единбурга, Шотландія. Паралельно з гризенням граніту науки молодий чоловік відвідував заняття в Центральній школі Мовлення та Драми в Лондоні, Англія.",
                            ImageName = "da0240d0882b4ec1942342ec6cf72505.jpg",
                            IsOscar = false,
                            Name = "Енгус",
                            Surname = "Макфадьєн"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1966, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 8,
                            Description = "Народилася 17 листопада 1966 року в Париж, Франція.\r\n\r\nПрославилася підлітком, дебютувавши у «Вечірці» (La Boum, 1980). Вдало знайдений образ «ідеальної французької дівчини», якою Марсо визнали за підсумками глядацького опитування, було розмножено у фільмах «Вечірка-2» (фр. La Boum 2, 1982), «Щасливого Великодня» (1984), «Студентка» (1988), «Аромат кохання. Фанфан» (1993) тощо. Актрису часто залучали до найамбітніших проектів національної кіноіндустрії: «Форт Саґан», «Шуани!», «Дочка Д'Артаньяна», де вона втілювала ідеальну француженку, перетворившись із чарівного підлітка на одну з найкрасивіших актрис світового кіно.\r\n\r\n1999 року зіграла дівчину Бонда у черговому, 19-му за ліком, епізоді Бондіани — підступну, але дуже вразливу Електру Кінґ. Продовжує активно зніматися.",
                            ImageName = "c9b0972dd8b6431193cd50e9c272416f.jpg",
                            IsOscar = false,
                            Name = "Софі",
                            Surname = "Марсо"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 22,
                            Description = "Крістофер Джонатан Джеймс Нолан - англійський кінорежисер, сценарист і продюсер, який має британське і американське громадянства.[3][4][5] Його 12 фільмів були схвально прийняті світовою кінокритикою та зібрали понад 4 млрд доларів касових зборів, що робить його одним з найуспішніших режисерів сучасності.\r\n\r\nОтримав перше визнання після виходу психологічного трилера Мементо (2000), композиція якого побудована на викривленнях часу. Це дало йому змогу зняти високобюджетний трилер Безсоння (2002) та драму Престиж (2006). Подальший успіх режисерові принесли трилогія Темний лицар (2005—2012), фільм про проникання в чужі сни Початок (2010), науково-фантастичний фільм Інтерстеллар (2014), військову драму Дюнкерк (2017) та науково-фантастичний бойовик Тенет (2020).",
                            ImageName = "2dbb31f7096740559fba2c8a22a870b2.jpg",
                            IsOscar = false,
                            Name = "Крістофер",
                            Surname = "Нолан"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 2,
                            Description = "Леона́рдо Вільгельм Ді Ка́пріо (англ. Leonardo Wilhelm DiCaprio; нар. 11 листопада 1974, Лос-Анджелес, США) — американський актор, кінопродюсер. Лауреат премії «Оскар» за найкращу чоловічу роль у фільмі «Легенда Г'ю Гласса» (2016), та нагороди BAFTA і Гільдії кіноакторів США за виконання ролі Г'ю Гласса. Лауреат трьох премій «Золотий глобус» у категорії «Найкращий актор в драматичній картині» і «Найкращий актор — комедія або мюзикл» за головні ролі в картинах «Авіатор», «Вовк з Уолл-стріт» і «Легенда Г'ю Гласса». Лауреат нагороди Берлінського кінофестивалю «Срібний ведмідь» в категорії «Найкращий актор» за виконання ролі Ромео Монтеккі в картині «Ромео + Джульєтта».\r\n\r\nПовноцінну акторську кар'єру почав в шістнадцять років на початку 1990-х років. У 2000-х роках отримав визнання публіки і критиків за роботу в широкому діапазоні кіно і акторську майстерність.",
                            ImageName = "1d4e8a9fea6146a887c774ffa2db33d7.jpg",
                            IsOscar = true,
                            Name = "Леонардо",
                            Surname = "Ді Капріо"
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateTime(1977, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 20,
                            Description = "Едвард Томас Гарді (англ. Edward Thomas Hardy) (нар. 15 вересня 1977, Гаммерсміт, Лондон, Велика Британія), знаніший як Том Гарді (англ. Tom Hardy) — британський актор театру та кіно, відомий за головною роллю у фільмі «Бронсон» (2009), а також завдяки участі в голлівудських блокбастерах «Зоряний шлях: Відплата» (2002), «Початок» (2010), «Воїн» (2011) та «Темний лицар повертається» (2012), «Шалений Макс: Дорога гніву» (2015), «Легенда Г'ю Гласса» (2015)",
                            ImageName = "42713c2fa8b64141a74b4fa6b3d05a0c.jpg",
                            IsOscar = false,
                            Name = "Том",
                            Surname = "Харді"
                        },
                        new
                        {
                            Id = 7,
                            Birthdate = new DateTime(1975, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 8,
                            Description = "Маріо́н Котія́р (фр. Marion Cotillard; нар. 30 вересня 1975, Париж, Франція) — французька акторка театру, телебачення та кіно. Володарка премій Оскар, Золотий глобус та BAFTA. Кавалерка та офіцерка ордена мистецтв та літератури.\r\n\r\nЗа роль у стрічці «Довгі заручини» (2004) отримала премію «Сезар» у номінації «Найкраща акторка другого плану». 2008 року удостоєна премії «Оскар» у номінації «Найкраща акторка» за фільм «Життя у рожевому кольорі», в якому виконала роль Едіт Піаф. Маріон Котіяр стала другою акторкою, що здобула премію «Оскар» за роль у фільмі іноземною мовою. Раніше цей рекорд утримувала Софі Лорен, володарка «Оскар» 1962 року. Також за фільм «Життя у рожевому кольорі» Котіяр отримала премію «Золотий глобус» у номінації «Найкраща жіноча роль (комедія або мюзикл)» і премію Британської академії телебачення та кіномистецтва (BAFTA) у номінації «Найкраща акторка».",
                            ImageName = "a9141daeb1e04aff947474ad3f2d07d7.jpg",
                            IsOscar = true,
                            Name = "Маріон",
                            Surname = "Котіяр"
                        },
                        new
                        {
                            Id = 8,
                            Birthdate = new DateTime(1933, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 20,
                            Description = "Сер Мо́ріс Джо́зеф Міклвайт (англ. Sir Maurice Joseph Micklewhite), відоміший за акторським (артистичним) псевдонімом як Майкл Кейн (англ. Michael Caine, народився 14 березня 1933 в Лондоні) — один з найпопулярніших британських акторів (знявся більш ніж у 100 фільмах). Це один з двох акторів (другий — Джек Ніколсон), який був номінований на премію «Оскар» у 1960-х, 1970-х, 1980-х, 1990-х та 2000-х роках.",
                            ImageName = "7adf0a94c3da4d8ea8809a79c6ea3eda.jpg",
                            IsOscar = true,
                            Name = "Майкл",
                            Surname = "Кейн"
                        },
                        new
                        {
                            Id = 9,
                            Birthdate = new DateTime(1976, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 23,
                            Description = "Кілліан Мерфі (англ. Cillian Murphy; нар. 25 травня 1976, Дуглас, графство Корк, Ірландія) — ірландський актор театру і кіно. Колишній співак, гітарист та автор пісень гурту The Sons of Mr. Green Genes. Наприкінці 90-х почав свою акторську кар'єру граючи на сцені, в короткометражних та незалежних фільмах. Свою першу помітну роль він зіграв у фільмі \"28 днів потому\" (2002), в чорній комедії \"Розрив\" (2003), в трилері \"Нічний рейс\" (2005). Також зіграв ірландську жінку-трансвестита в комедійній драмі \"Сніданок на Плутоні\" (2005), за що був номінований на премію Золотий глобус в категорії \"найкращий актор в мюзиклі або комедії\". З 2013 по 2022 знімався у кримінально-драматичному серіалі \"Гострі картузи\", де зіграв Томаса Шелбі.",
                            ImageName = "f39d0a89af744d498bc8aac540fefe4d.jpg",
                            IsOscar = true,
                            Name = "Кілліан",
                            Surname = "Мерфі"
                        },
                        new
                        {
                            Id = 10,
                            Birthdate = new DateTime(1981, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 2,
                            Description = "Джозеф Леонард Гордон-Левітт (англ. Joseph Leonard Gordon-Levitt; нар. 17 лютого 1981, Лос-Анджелес, Каліфорнія, США) — американський актор, режисер, сценарист та продюсер. Отримав популярність завдяки ролі Томмі Соломона у комедійному серіалі «Третя планета від Сонця» (1996—2001), а також фільмам «Цеглина» (2005), «500 днів літа» (2009), «Початок» (2010), «Темний лицар повертається» (2012) та «Петля часу».",
                            ImageName = "7d4159900afd4481881c42483b369f3e.jpg",
                            IsOscar = false,
                            Name = "Джозеф",
                            Surname = "Гордон-Левітт"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.StafMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("StafId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("StafId");

                    b.ToTable("StafMovie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            StafId = 1
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            StafId = 2
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            StafId = 3
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 2,
                            StafId = 4
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 2,
                            StafId = 5
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            StafId = 6
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 2,
                            StafId = 7
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 2,
                            StafId = 8
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 2,
                            StafId = 9
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 2,
                            StafId = 10
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.StafRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("StafRole", t =>
                        {
                            t.HasCheckConstraint("Name_check", "[Name] <> ''")
                                .HasName("Name_check7");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Режисер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Актор"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Оператор"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Продюсер"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Автор сценарію"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PremiumDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PremiumId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PremiumId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f66e492517d7414495e988c4c50fd107",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1998, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "1081e300-9fdb-42ff-acb2-7f72a856f94e",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Петро",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKcl2LRk7Ekv4urKEpqCCbmwlikV547N2bMSlkBtbk/JxCGhWry8QL8SQMi73Fv7dA==",
                            PhoneNumberConfirmed = false,
                            PremiumDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PremiumId = 1,
                            SecurityStamp = "7b81b2b6-b486-4a02-925f-f1a6ccf79115",
                            Surname = "Левак",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        },
                        new
                        {
                            Id = "d1901b2435594da2a255db13fc57509b",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1988, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "b575fdad-1761-4b42-b5be-2d2e9138e308",
                            Email = "User1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Iван",
                            NormalizedUserName = "USER1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxxBWekRvmifB8DEcj9bjuIxdNPDnVplET6DjWCYPLesUZa6eLi9Qds+Bor16hYww==",
                            PhoneNumberConfirmed = false,
                            PremiumDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PremiumId = 1,
                            SecurityStamp = "67e052f0-a426-48ad-9f26-750d6ca5beb7",
                            Surname = "Калита",
                            TwoFactorEnabled = false,
                            UserName = "User1@gmail.com"
                        },
                        new
                        {
                            Id = "c86dc56aedf549f6afe5ceb4d414ebf1",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(2000, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "8b097e84-b1c8-475a-ac54-3b8b1256c560",
                            Email = "User2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Петро",
                            NormalizedUserName = "USER2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEt48D02Nj5GWxXaJiRgYa995mXs33PAR7psuhSQaR/L5DnskFCfzgZPCoBJ1/Q6JA==",
                            PhoneNumberConfirmed = false,
                            PremiumDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PremiumId = 2,
                            SecurityStamp = "4f233df2-116b-4ba0-91bf-16496d48f3de",
                            Surname = "Дякуленко",
                            TwoFactorEnabled = false,
                            UserName = "User2@gmail.com"
                        },
                        new
                        {
                            Id = "028582c83a914a45b330b5234f4131fb",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1999, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "0b09a82a-6060-4290-bb06-c672591f2c33",
                            Email = "User3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Олег",
                            NormalizedUserName = "USER3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDu1p9wtLmMGShJwRO6uVb0CVDY9lAP2LhLrNFA3/7R6sFD80b7RBLD/sddC9lSIjA==",
                            PhoneNumberConfirmed = false,
                            PremiumDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PremiumId = 3,
                            SecurityStamp = "87cf9351-74a6-4136-b637-be8e27b22255",
                            Surname = "Панасенко",
                            TwoFactorEnabled = false,
                            UserName = "User3@gmail.com"
                        },
                        new
                        {
                            Id = "eb05f9548a2c4cf8adcc2be7305fc732",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(2001, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "d5035b34-ccc0-4453-8abb-dd73d7dec8d6",
                            Email = "User4@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Тимофій",
                            NormalizedUserName = "USER4@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHPxB/eNnGHbQAZ0siUDXf4ABIjXM9xH9NM2LpqkcH/+bZTgM4I2ik095zPCbRE2QA==",
                            PhoneNumberConfirmed = false,
                            PremiumDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PremiumId = 2,
                            SecurityStamp = "7a94f900-18ae-4191-b64c-8ca2db949ae4",
                            Surname = "Гнатенко",
                            TwoFactorEnabled = false,
                            UserName = "User4@gmail.com"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.UserMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMovie");
                });

            modelBuilder.Entity("DataAccess.Data.StafStafRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StafId")
                        .HasColumnType("int");

                    b.Property<int>("StafRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StafId");

                    b.HasIndex("StafRoleId");

                    b.ToTable("StafStafRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StafId = 1,
                            StafRoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            StafId = 1,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            StafId = 1,
                            StafRoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            StafId = 2,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            StafId = 3,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            StafId = 4,
                            StafRoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            StafId = 5,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            StafId = 6,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            StafId = 7,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            StafId = 8,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            StafId = 9,
                            StafRoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            StafId = 10,
                            StafRoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "15b04d9eff654d8d966a172db59e2722",
                            ConcurrencyStamp = "15b04d9eff654d8d966a172db59e2722",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "59139483f3d1417db1efee50d14b6a7f",
                            ConcurrencyStamp = "59139483f3d1417db1efee50d14b6a7f",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f66e492517d7414495e988c4c50fd107",
                            RoleId = "15b04d9eff654d8d966a172db59e2722"
                        },
                        new
                        {
                            UserId = "d1901b2435594da2a255db13fc57509b",
                            RoleId = "59139483f3d1417db1efee50d14b6a7f"
                        },
                        new
                        {
                            UserId = "c86dc56aedf549f6afe5ceb4d414ebf1",
                            RoleId = "59139483f3d1417db1efee50d14b6a7f"
                        },
                        new
                        {
                            UserId = "028582c83a914a45b330b5234f4131fb",
                            RoleId = "59139483f3d1417db1efee50d14b6a7f"
                        },
                        new
                        {
                            UserId = "eb05f9548a2c4cf8adcc2be7305fc732",
                            RoleId = "59139483f3d1417db1efee50d14b6a7f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Feedback", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Movie", "Movie")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Image", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Movie", "Movie")
                        .WithMany("ScreenShots")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Movie", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Country", "Country")
                        .WithMany("Movies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Premium", "Premium")
                        .WithMany("Movies")
                        .HasForeignKey("PremiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Quality", "Quality")
                        .WithMany("Movies")
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Premium");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.MovieGenre", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Staf", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Country", "Country")
                        .WithMany("Stafs")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.StafMovie", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Movie", "Movie")
                        .WithMany("StafMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Staf", "Staf")
                        .WithMany("StafMovies")
                        .HasForeignKey("StafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Staf");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Premium", "Premium")
                        .WithMany("Users")
                        .HasForeignKey("PremiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premium");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.UserMovie", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Movie", "Movie")
                        .WithMany("UserMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.User", "User")
                        .WithMany("UserMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Data.StafStafRole", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Staf", "Staf")
                        .WithMany("StafStafRoles")
                        .HasForeignKey("StafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.StafRole", "StafRole")
                        .WithMany("StafStafRoles")
                        .HasForeignKey("StafRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Staf");

                    b.Navigation("StafRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Country", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Stafs");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Movie", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("MovieGenres");

                    b.Navigation("ScreenShots");

                    b.Navigation("StafMovies");

                    b.Navigation("UserMovies");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Premium", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Quality", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Staf", b =>
                {
                    b.Navigation("StafMovies");

                    b.Navigation("StafStafRoles");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.StafRole", b =>
                {
                    b.Navigation("StafStafRoles");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("UserMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
